apiVersion: lldap-operator.lukidoescode.com/v1alpha1
kind: LldapAttributeSchema
metadata:
  name: department
  labels:
    lldap-operator.lukidoescode.com/lldap-instance: default
spec:
  attributeName: "department"
  attributeType: "String"
  target: "User"
  isList: false
  isVisible: true
  isEditable: true
