apiVersion: lldap-operator.lukidoescode.com/v1alpha1
kind: LldapMembership
metadata:
  name: alice-engineering
  labels:
    lldap-operator.lukidoescode.com/lldap-instance: default
spec:
  userName: "alice.smith"
  groupName: "Engineering"
