replicaCount: 1

image:
  repository: ghcr.io/lukidoescode/lldap-resources-operator
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

lldap:
  url: "http://lldap:17170"
  credentialsSecret: "lldap-admin-credentials"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
