apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lldap-resources-operator.fullname" . }}
  labels:
    {{- include "lldap-resources-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lldap-resources-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lldap-resources-operator.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lldap-resources-operator.serviceAccountName" . }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LLDAP_URL
              value: {{ .Values.lldap.url | quote }}
            - name: LLDAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.lldap.credentialsSecret }}
                  key: username
            - name: LLDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.lldap.credentialsSecret }}
                  key: password
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
